apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: 307000127327.dkr.ecr.ap-south-1.amazonaws.com/nodeapp:1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

